### PR TITLE
KNDP-29: OCI build and push action to "release/**" branches

### PR DESCRIPTION
**Pull request by Enotmd**

### CODE REVIEW

**Review by web7evgheni — CHANGES_REQUESTED** [review]

**Comment by web7evgheni** [comment]
@art10m Go sleep! 💤

**Comment by web7evgheni** [comment]
@Enotmd Please resolve conflicts

**Review by art10m — CHANGES_REQUESTED** [review]
@Enotmd resolve conflicts for changed files

**Review by web7evgheni — APPROVED** [review]

**Review by web7evgheni — DISMISSED** [review]

**Review by art10m — APPROVED** [review]

**Comment by web7evgheni** [comment]
@Enotmd Again conflicts

**Review by art10m — APPROVED** [review]

**Review by web7evgheni — APPROVED** [review]

**Pull request merged**
