### PR TITLE
Bugfix/kndp 21 development portal helm chart

### PR DESCRIPTION
**Pull request by Timex1854**

### CODE REVIEW

**Review by web7evgheni — CHANGES_REQUESTED** [review]
Please resolve conflicts.

**Review by web7evgheni — COMMENTED** [review]
Did you test it?

**Comment by Timex1854** [comment]
I tested it, it works as expected

**Review by web7evgheni — APPROVED** [review]

**Comment by web7evgheni** [comment]
Please update your branch from 0.1 and resolve conflicts

**Review by web7evgheni — APPROVED** [review]

**Pull request merged**
